### ISSUE TITLE
有部分Emoji没有拦截到

### ISSUE THREAD

**Issue by uccmawei** [woxingxiao/XEditText#10]
![device-2017-07-17-144522](https://user-images.githubusercontent.com/19404384/28257615-c60125e8-6afe-11e7-9b96-b0c45145aa10.png)

小米5，安卓7.0，讯飞输入法。

**Comment by woxingxiao** [comment]
嗯确实，搜狗输入法也这样。不是什么硬伤，毕竟鲜有机会用到这几个，后续再做改进吧。
