### ISSUE TITLE
清除的Drawable显示不出来

### ISSUE THREAD

**Issue by weiningpeng** [woxingxiao/XEditText#11]
当为XEditText添加android:gravity = center属性时，清除的Drawable图标不见了，但是那个眼睛还在。
我在清除drawable的图标的位置上点击，EditText的内容还是会被清除。
这应该是一个BUG

**Comment by woxingxiao** [comment]
当使用密码的时候，ClearDrawable实际是在onDraw里画出来的。当你继承`EditText`在onDraw里绘制内容，同时设置了Gravity为`center` `center_vertical` `right` `end` 中的任何一种，绘制内容就无法显示。网上也有其他人遇到过这个问题，原因尚不明确。
