### ISSUE TITLE
清除密码的按键无法显示

### ISSUE THREAD

**Issue by kazeik** [woxingxiao/XEditText#13]
按以下布局来写，清除密码的按键总是显示不出来。
<com.xw.repo.XEditText
            android:id="@+id/et_new_password"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:background="@null"
            android:gravity="right"
            android:hint="请输入新密码"
            android:imeOptions="actionDone"
            android:inputType="textPassword"
            android:singleLine="true"
            android:textSize="14sp"
            app:x_clearDrawable="@drawable/delete_selector" />

**Comment by woxingxiao** [comment]
app:x_clearDrawable="" ？这样显示个鬼啊。。

**Comment by kazeik** [comment]
<com.xw.repo.XEditText
            android:id="@+id/et_old_password"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@null"
            android:gravity="right|center_vertical"
            android:hint="请输入原密码"
            android:imeOptions="actionNext"
            android:inputType="textPassword"
            android:maxLength="16"
            android:paddingRight="@dimen/dp_5"
            android:singleLine="true"
            android:textSize="14sp"
            app:x_clearDrawable="@drawable/delete_selector"/>

这样也不显示好吗。
我没有写全。是觉得你能看懂。没想到你看不懂。

**Comment by woxingxiao** [comment]
1. 按照兄台的说法，就好像去医院看病，就给医生说我肚子痛，你不把我治好我可是要闹事的；
2. 大家都很忙，凭什么让别人来揣测您的想法并把为您服务好，要不您办个VIP会员？
3. Demo现成的，和自己的对比一下不就发现问题了？
4. 取消gravity = right（不支持的原因一是原理上，二是没有这种交互）
