### ISSUE TITLE
删除按钮和隐藏按钮不对称

### ISSUE THREAD

**Issue by tpnet** [woxingxiao/XEditText#15]
小米2
Android5.0

 
![login_btn_delete 3x](https://user-images.githubusercontent.com/17380722/33511143-b2cfff44-d750-11e7-9cd3-c746b619b526.png)

![login_btn_hide 3x](https://user-images.githubusercontent.com/17380722/33511145-b78b1078-d750-11e7-8a95-b1d3fbe964f0.png)

![screenshot_2017-12-02-10-58-39-548_com shhuoniu txhui](https://user-images.githubusercontent.com/17380722/33511147-bbe4d8a2-d750-11e7-8ffc-c25a2d88285a.png)

**Comment by tpnet** [comment]
没有垂直居中

**Comment by woxingxiao** [comment]
你眼睛图标的问题。

**Comment by tpnet** [comment]
@woxingxiao  不是，我在小米note上没事的，在小米2上就出现这样子的情况。


我小米note的截图：
![image](https://user-images.githubusercontent.com/17380722/33511514-d0072f8c-d756-11e7-8665-ca900aab39fa.png)

**Comment by woxingxiao** [comment]
我用你的图在720P屏幕上试过没有问题，你让UI重新切个完全居中的图标再试试，或者看看图标是不是放在不合适dpi的文件夹下了。

**Comment by tpnet** [comment]
@woxingxiao  大佬，不是图片问题啊，，我用 你的demo在 小米2Android5.0上跑，也是一样，没有垂直居中，，，
![image](https://user-images.githubusercontent.com/17380722/35204389-b5a6c104-ff68-11e7-9537-2fe2a7cf8d65.png)

**Comment by woxingxiao** [comment]
@tpnet 这个X是相对View高度居中，你可以发现你这部手机它的内容区并不垂直居中（或者说偏得比较多），目前没有找到比较好的解决方案。
在我看来，你不必纠结这一个机型，毕竟小米2都被淘汰多年了。如果你是强迫症，你可以使用ImageView来实现眼睛图标。
