### ISSUE TITLE
反馈两个问题

### ISSUE THREAD

**Issue by bravecheng** [woxingxiao/XEditText#18]
1.密码长度默认设置为20了，无法输入超过20位的密码
2.超过长度以后，删除按钮会出现位置错乱

**Comment by woxingxiao** [comment]
什么样的密码会超过20位？我限制了密码长度，不限制的话密码会延伸到X按钮的下层，看起来很尴尬

**Comment by bravecheng** [comment]
wifi密码允许的设置长度是 6-32位，这个长度会超的，建议适配下X按钮的问题

**Comment by woxingxiao** [comment]
原因我已经说了，太长会重叠（删除X是画上去的），再者没有谁会真正设置那么长的密码。如果你非要解除限制，在Activity里设置下EditText的长度即可。
