### ISSUE TITLE
由于焦点的问题一直认为IOS style没有作用

### ISSUE THREAD

**Issue by ysmintor** [woxingxiao/XEditText#2]
测试后发现单个edittext获得焦点，就没有默认的动画效果了

**Comment by woxingxiao** [comment]
的确是这样，感谢你的反馈。
可以有两种解决方案：
1.简单的方式。使用两个`XEditText`上下排布，上面的设置`width="0dp"`，下面的开启`iOSStytle`，经测试可行。
2.优雅但麻烦的方式。首先重写`EditText`所在的最顶层布局，在`onLayout()`方法中通过判断输入法弹起和隐藏造成的根布局高度的变化，来实现对输入法弹起和隐藏状态的监听[（参考链接）](http://blog.csdn.net/top_code/article/details/9187481)。其次，仿造`XEditText`中`iOSStyle`部分的实现，自定义一个`EditText`，通过监听输入法状态来开关`iOSStyle`。

Enjoy.

**Comment by ysmintor** [comment]
我目前一个简单的办法，就是一进去activity后让这个view得到焦点
```java
<View
                android:layout_width="0dp"
                android:layout_height="0dp"
                android:focusable="true"
                android:focusableInTouchMode="true"/>

```

**Comment by woxingxiao** [comment]
因缺思婷，达到目的就行。

**Comment by woxingxiao** [comment]
朋友，喜欢就star一个呗
