### ISSUE TITLE
在XML设置了digits属性之后，密码是否明文的按钮，无法显示

### ISSUE THREAD

**Issue by PiPiCaptain** [woxingxiao/XEditText#21]
如标，代码如下：
<com.xw.repo.XEditText
            android:id="@+id/etPw"
            android:layout_width="match_parent"
            android:layout_height="40dp"
            android:layout_gravity="center_vertical"
            android:layout_marginEnd="5dp"
            android:layout_marginLeft="5dp"
            android:layout_marginRight="5dp"
            android:layout_marginStart="5dp"
            android:background="@null"
            android:digits="@string/filter_code"
            android:hint="@string/goldcoin_register_pw_hint"
            android:inputType="textPassword"
            android:maxLength="20"
            android:maxLines="1"
            android:textColor="@color/txt_666"
            android:textColorHint="@color/txt_666"
            android:textSize="14sp" />

**Comment by woxingxiao** [comment]
加上digits后InputType变了，很奇怪，导致无法自动识别为密码输入类型。现在我已经改进，可以直接设置`app:x_togglePwdDrawableEnable="true"`来强制显示。

**Comment by PiPiCaptain** [comment]
@woxingxiao 好的，感谢
