### ISSUE TITLE
请问java用法中，将xEditText设置为密码输入是直接setInputType?

### ISSUE THREAD

**Issue by DeveloperHu** [woxingxiao/XEditText#27]
希望能出一份  xml属性对应的Java用法文档 好参考 谢谢大大

**Comment by woxingxiao** [comment]
只能通过xml设置，因为没有想到太多场景需要动态改变是否密码输入类型。你的场景是？

**Comment by DeveloperHu** [comment]
我现在将xEditText和其他组件封装成一个layout  当我传入相应的值的时候  可以改变xEditText的类型
想这么做，请问可以xEditText搞一个方法暴露出来，让我能改变他的输入类型吗？
比如手机号输入就输入手机号，密码输入就输入密码类型这样子

**Comment by woxingxiao** [comment]
@DeveloperHu 新版支持了，java通过`setInputType()`设置。

**Comment by DeveloperHu** [comment]
@woxingxiao 谢谢
