### ISSUE TITLE
Galaxy S7 Edge

### ISSUE THREAD

**Issue by azhangheng** [woxingxiao/XEditText#28]
Attempt to invoke virtual method 'android.content.ClipData$Item android.content.ClipData.getItemAt(int)' on a null object reference
com.xw.repo.XEditText.onTextContextMenuItem(XEditText.java:312)

**Comment by woxingxiao** [comment]
百分之百崩？

**Comment by azhangheng** [comment]
对，从360应用市场 云测试中发现每次都报这个错误，都是这一个机型，由于我这里没有这款测试机，无法进行确认问题具体原因。

**Comment by azhangheng** [comment]
java.lang.NullPointerException

Attempt to invoke virtual method 'android.content.ClipData$Item android.content.ClipData.getItemAt(int)' on a null object reference

1 com.xw.repo.XEditText.onTextContextMenuItem(XEditText.java:312)
--
2 android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:4148)
3 com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2769)
4 com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:95)
5 com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
6 com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:157)
7 com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
8 com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
9 com.android.internal.view.FloatingActionMode$4.onMenuItemClick(FloatingActionMode.java:124)
10 com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$3.onClick(FloatingToolbar.java:414)
11 android.view.View.performClick(View.java:6213)
12 android.widget.TextView.performClick(TextView.java:11074)
13 android.view.View$PerformClick.run(View.java:23645)
14 android.os.Handler.handleCallback(Handler.java:751)
15 android.os.Handler.dispatchMessage(Handler.java:95)
16 android.os.Looper.loop(Looper.java:154)
17 android.app.ActivityThread.main(ActivityThread.java:6646)
18 java.lang.reflect.Method.invoke(Native Method)
19 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
20 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

希望能让你更容易找出问题所在。
