### ISSUE TITLE
有一个bug，华为手机自带的键盘，输入的时候，到最后一位就会自动删除。

### ISSUE THREAD

**Issue by liaopen123** [woxingxiao/XEditText#3]
把代码里面的这一行注释掉就行了。
lse if (preLength <= maxLength) { // 正在删除
                        Logger.d(TAG,"preLength"+preLength+"，，maxLength，"+maxLength);
                        Logger.d(TAG,"正在删除");
                        removeTextChangedListener(mTextWatcher);
                        mTextWatcher = null;
                     //   getText().delete(currLength - 1, currLength);
                    }

**Comment by woxingxiao** [comment]
这段代码逻辑是自动删除分隔符的，刚用华为测试了也没问题

**Comment by liaopen123** [comment]
用华为手机的自带的键盘发现了这个bug，你试试

**Comment by woxingxiao** [comment]
请问具体表现是怎样的，我不太明白

**Comment by liaopen123** [comment]
我等会拍个视频 给你看看
