### ISSUE TITLE
少一个可以设置显示或隐藏清除按钮的函数

### ISSUE THREAD

**Issue by sunshine178** [woxingxiao/XEditText#30]
希望可以在代码中也可以调用，方便使用更多场景需求。

**Comment by HenryForChina** [comment]
> 
> 
> 希望可以在代码中也可以调用，方便使用更多场景需求。
setRightMarkerDrawable(null);
设置这行代码就可以了

**Comment by woxingxiao** [comment]
XEditText.setDisableClear(true);
