### ISSUE TITLE
2.2.4 maxLength 属性无效

### ISSUE THREAD

**Issue by ayuhani** [woxingxiao/XEditText#35]

**Comment by PioMarioJonathan** [comment]
Hi, I have the same problem. I'm not able to set the maxLength property working... For example, as this snippet of code reports, this input should prevent typing more than 128 characters, but I can write infinite chars! How can I make the rule valid and working?

`<com.xw.repo.XEditText
                android:id="@+id/textViewTaskNote"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_marginStart="12dp"
                android:layout_marginTop="6dp"
                android:layout_marginEnd="6dp"
                android:padding="6dp"
                android:layout_toStartOf="@+id/btnTaskSendNoteAction"
                android:background="@drawable/edit_text_rounded_task_note"
                android:fontFamily="@font/open_sans"
                android:maxLines="3"
                android:maxLength="128"
                android:hint="@string/app_task_contact_hint_note"
                android:inputType="textMultiLine"
                android:textColorHint="@color/colorCmaTextLightGray2"
                android:textColor="@color/colorCmaTextGray"
                android:textSize="13sp"
                app:x_disableEmoji="true"
                app:x_clearDrawable="@drawable/icon_clear_input_task_note"/>`

**Comment by JakeWoki** [comment]
maxLength和x_disableEmoji属性冲突

**Comment by woxingxiao** [comment]
已修复。
