### ISSUE TITLE
为什么在onTouchEvent里actiontype=UP的时候要performclick呢？

### ISSUE THREAD

**Issue by fansangg** [woxingxiao/XEditText#39]
我设置了clicklistener 但是会触发两次，看见源码里actionup的时候调了performclick，出于什么目的？

**Comment by woxingxiao** [comment]
重写onTouchEvent的时候AS会警告让手动调用performclick，强迫症驱使我在ACTION_UP的时候去调用了，警告消失。新版已去掉。
