### ISSUE TITLE
希望可以增加几个函数，允许设置清除按钮和显示隐藏密码按钮的距离，以及增大按钮的点击范围

### ISSUE THREAD

**Issue by ligong0904** [woxingxiao/XEditText#41]
如题：
1. 清除按钮和显示隐藏密码按钮个人感觉离得有点近，有时候容易误触，希望作者可以允许开发者自定义两个按钮之间的距离。
2. 希望作者可以适当增大一点按钮的点击范围。

**Comment by woxingxiao** [comment]
给给给！好评哦亲😄
