### ISSUE TITLE
密码框输入过长时，清除图标移动适配可以这样修改（仅供参考）

### ISSUE THREAD

**Issue by hzq19920817** [woxingxiao/XEditText#43]
本着不大改的逻辑，因为删除按钮是绘制上去的，唯一问题就是当输入框内容过多，内容就可以滚动，就会把删除按钮顶掉，
所以需要在长度部分加上滚动的距离就行，（唯一需要注意的就是在xml里面把drawablePadding设置你删除按钮的宽度+间距即可），仅供参考

@Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        if (hasFocused && mBitmap != null && isPwdInputType && !isTextEmpty()) {
            if (mLeft * mTop == 0) {
                mLeft = getMeasuredWidth() - getPaddingRight() -
                        mTogglePwdDrawable.getIntrinsicWidth() - mBitmap.getWidth() - mPadding;
                mTop = (getMeasuredHeight() - mBitmap.getHeight()) >> 1;
            }
            if (getScrollX() > 0) {
                canvas.drawBitmap(mBitmap, mLeft + getScrollX(), mTop, null);
            } else {
                canvas.drawBitmap(mBitmap, mLeft, mTop, null);
            }
        }
    }

**Comment by woxingxiao** [comment]
> 本着不大改的逻辑，因为删除按钮是绘制上去的，唯一问题就是当输入框内容过多，内容就可以滚动，就会把删除按钮顶掉，
> 所以需要在长度部分加上滚动的距离就行，（唯一需要注意的就是在xml里面把drawablePadding设置你删除按钮的宽度+间距即可），仅供参考
> 
> @override
> protected void onDraw(Canvas canvas) {
> super.onDraw(canvas);
> if (hasFocused && mBitmap != null && isPwdInputType && !isTextEmpty()) {
> if (mLeft * mTop == 0) {
> mLeft = getMeasuredWidth() - getPaddingRight() -
> mTogglePwdDrawable.getIntrinsicWidth() - mBitmap.getWidth() - mPadding;
> mTop = (getMeasuredHeight() - mBitmap.getHeight()) >> 1;
> }
> if (getScrollX() > 0) {
> canvas.drawBitmap(mBitmap, mLeft + getScrollX(), mTop, null);
> } else {
> canvas.drawBitmap(mBitmap, mLeft, mTop, null);
> }
> }
> }

好的，我有空验证下，感谢
