### ISSUE TITLE
在输入的时候，按右边的X号不能清除

### ISSUE THREAD

**Issue by dasenlin2013** [woxingxiao/XEditText#5]
效果和按输入框中间一样，键盘落下马上又弹起来

**Comment by woxingxiao** [comment]
请问你什么手机，系统版本？顺便帖下你的xml

**Comment by dasenlin2013** [comment]
模拟器，7.0，activity设置adjustPan后，输入框上移了。我跟踪了一下，发现此时event.getY 得到的是负值

**Comment by woxingxiao** [comment]
照理说adjustPan输入框是不会动的，我这里设置adjustResize输入框上移、删除是没有问题的，你试试

**Comment by dasenlin2013** [comment]
找到问题了，和XEditText没关系，是我自己代码的问题。
因为要实现点击空白处收起键盘的功能，按照一篇文章里的方法，在base activity里重写了事件处理方法，就是这个文章的第二个方法 http://blog.csdn.net/mad1989/article/details/25069821，但是点击删除图标时，isShouldHideInput判断不是在edittext里。 把这个去掉就好了，不过就不能方便的点击空白收起键盘了。

**Comment by woxingxiao** [comment]
可以为当前Activity的RootView设置OnClickListener，监听里使用下面代码实现隐藏软键盘：
```java
InputMethodManager inputManager = (InputMethodManager) .getSystemService(Context.INPUT_METHOD_SERVICE);
inputManager.hideSoftInputFromWindow(mEditText.getWindowToken(), 0);
```

**Comment by dasenlin2013** [comment]
这个方法也行，我试试加到base activity里
