### ISSUE TITLE
Bug backspace after emoji filtered

### ISSUE THREAD

**Issue by hendrawd** [woxingxiao/XEditText#7]
Step to reproduce:
1. Enter any text >= 2 characters
2. Input any emoji
3. Press backspace
4. 2 characters is deleted instead of 1

**Comment by koksalb** [comment]
I can confirm this. But it doesn't seem to happen on every emoji. So I am a bit confused.

**Comment by hendrawd** [comment]
Really? What kind of emoji that doesn't trigger it?

**Comment by hendrawd** [comment]
Actually there are more case...
⚫⚪ will only delete 1 character
🇦🇩🇦🇪🇦🇫, etc will delete 4 characters

**Comment by woxingxiao** [comment]
That's very odd because it's all perfect working on my phone. I wonder if it relates to language or soft input method you use some how...

**Comment by hendrawd** [comment]
I am using English (US) Android Keyboard(AOSP)
My phone is One Plus One
Device Model: A0001
Android Version: 7.1
Using CyanogenMod, version 14.1-20161123-NIGHTLY-bacon

I haven't tried using the other phone, will check later with other phone models

**Comment by woxingxiao** [comment]
Ok, I'll try ASOP on my phone to see what going to happen.

**Comment by hendrawd** [comment]
I tried on 2 more phone model and the problem still exist

Phone: Google Nexus 5
Android version: 5.0
Keyboard type: AOSP - English(US)

Phone: Google Nexus 5
Android version: 4.4.4
Keyboard type: AOSP - English(US)

I think we can use TextWatcher to filter manually instead of filter?
